-- Project: Rv-rental-app
-- Author: martin Chmelík
-- Email: chmelikmartin123@gmail.com
-- Creation date: 8. 1. 2026

create table brand(
id int generated by default as identity primary key,
name varchar(20) not null
);

create table rv_type(
id int generated by default as identity primary key,
name varchar(40) not null,
description varchar(40) not null
);

create table rv(
id int generated by default as identity primary key,
spz varchar(20) not null unique,
manufacture_date date not null,
price_for_day decimal(10, 2) not null,
id_brand int not null check(id_brand > 0),
id_type int not null check(id_type > 0),

foreign key(id_brand) references brand(id),
foreign key(id_type) references rv_type(id)
);

create table customer(
id int generated by default as identity primary key,
name varchar(30) not null,
surname varchar(30) not null,
email varchar(50) not null,
tel varchar(12) not null
);

create table accessory(
id int generated by default as identity primary key,
name varchar(40) not null,
description varchar(50) not null,
price_for_day decimal(10, 2) not null
);

create table rental(
id int generated by default as identity primary key,
date_from date not null,
date_to date not null,
creation_date date not null,
price decimal(10, 2) not null,
status varchar(20) not null check(status in ('reserved', 'active', 'finished', 'canceled')),
is_paid number(1,0) not null check(is_paid in (1, 0)),
id_customer int not null check(id_customer > 0),
id_rv int not null check(id_rv > 0),

check(date_from < date_to),

foreign key(id_customer) references customer(id),
foreign key(id_rv) references rv(id)
);

create table accessory_rental(
id int generated by default as identity primary key,
id_accessory int not null check(id_accessory > 0),
id_rental int not null check(id_rental > 0),
amount int not null check(amount > 0),
price_at_rent decimal(10, 2) not null,

foreign key(id_accessory) references accessory(id),
foreign key(id_rental) references rental(id)
);



INSERT INTO brand (name) VALUES ('Volkswagen');
INSERT INTO brand (name) VALUES ('Airstream');

INSERT INTO rv_type (name, description) 
VALUES ('Motorhome', 'Large vehicle with alcove bed');

INSERT INTO accessory (name, description, price_for_day) 
VALUES ('Camping Set', 'Table and 4 chairs', 150.00);
INSERT INTO accessory (name, description, price_for_day) 
VALUES ('Bike Rack', 'For 3 bicycles', 100.00);
INSERT INTO accessory (name, description, price_for_day) 
VALUES ('GPS Navigation', 'Pre-loaded with offline maps', 50.00);
       
       
INSERT INTO rv (spz, manufacture_date, price_for_day, id_brand, id_type) 
VALUES ('RV-99-SKY', '15-5-2025', 2500.00, 1, 1);
INSERT INTO rv (spz, manufacture_date, price_for_day, id_brand, id_type) 
VALUES ('VAN-22-ROAD', '10-1-2024', 1800.00, 2, 1);

INSERT INTO customer (name, surname, email, tel) 
VALUES ('John', 'Doe', 'john.doe@example.com', '477123456');
INSERT INTO customer (name, surname, email, tel) 
VALUES ('Alice', 'Smith', 'a.smith@provider.com', '779876543');
       
INSERT INTO rental (date_from, date_to, creation_date, price, status, is_paid, id_customer, id_rv) 
VALUES ('01-07-2026', '14-07-2026', '08-01-2026', 35000.00, 'reserved', 1, 1, 1);

INSERT INTO accessory_rental (id_accessory, id_rental, amount, price_at_rent) 
VALUES (1, 1, 1, 150.00);
INSERT INTO accessory_rental (id_accessory, id_rental, amount, price_at_rent) 
VALUES (2, 1, 1, 100.00);

create or replace procedure delete_rental_proc(
p_id_rental in int
)
as
begin
delete from accessory_rental where id_rental = p_id_rental;
delete from rental where id = p_id_rental;

commit;
exception
when others then
rollback;
raise;
end;
/


create or replace procedure create_rental_simple(
p_date_from in date,
p_date_to in date,
p_creation_date in date,
p_price in decimal,
p_id_customer in int,
p_id_rv in int
)
as
  v_cnt number;
begin
select count(*) into v_cnt
from rental
where id_rv = p_id_rv and status in ('reserved', 'active')and not (p_date_to   <= date_from or p_date_from >= date_to);

if v_cnt > 0 then
    raise_application_error(-20001, 'RV not available');
  end if;


insert into rental(date_from, date_to, creation_date,rental.price, status, is_paid, id_customer, id_rv)
values (p_date_from, p_date_to, p_creation_date,p_price, 'reserved', 0, p_id_customer, p_id_rv);

commit;
exception
when others then
rollback;
raise;
end;
/


create or replace procedure create_rental_with_acc(
p_date_from in date,
p_date_to in date,
p_creation_date in date,
p_price in decimal,
p_id_customer in int,
p_id_rv in int,
p_rental_id out int
)
as
v_cnt number;
begin
select count(*) into v_cnt
from rental
where id_rv = p_id_rv and status in ('reserved', 'active') and not (p_date_to <= date_from or p_date_from >= date_to);

if v_cnt > 0 then
raise_application_error(-20001, 'RV not available');
end if;

insert into rental(date_from, date_to, creation_date,price, status, is_paid, id_customer, id_rv)
values (p_date_from, p_date_to, p_creation_date,p_price, 'reserved', 0, p_id_customer, p_id_rv)
returning id into p_rental_id;

commit;
exception
when others then
rollback;
raise;
end;
/

create view v_rv_overview
as
select rv.id as rv_id, rv.spz, rv.manufacture_date, rv.price_for_day, brand.name as brand_name, rv_type.name as type_name, rv_type.description as type_description
from rv
join brand on rv.id_brand = brand.id
join rv_type on rv.id_type = rv_type.id;


create view v_rental_overview
as
select rental.id as rental_id, rental.date_from, rental.date_to, rental.creation_date, rental.price, rental.status, rental.is_paid, customer.name as customer_name, customer.surname as customer_surname, customer.email, rv.spz as rv_spz
from rental
join customer on rental.id_customer = customer.id
join rv on rental.id_rv = rv.id;

create view v_revenue_by_brand
as
select b.name as brand_name, COUNT(r.id) as total_rentals, SUM(r.price) as total_revenue, AVG(r.price) as avg_rental_price, MIN(r.price) as min_rental_price, MAX(r.price) as max_rental_price
from rental r
join rv on r.id_rv = rv.id
join brand b on rv.id_brand = b.id
where r.status != 'canceled'
group by b.name;

create view v_customer_statistics
as
select c.id as customer_id, c.name || ' ' || c.surname as customer_name, c.email, COUNT(r.id) as total_rentals, SUM(r.price) as total_spent, AVG(r.date_to - r.date_from) as avg_rental_days
from customer c
join rental r on c.id = r.id_customer
group by c.id, c.name, c.surname, c.email;

create view v_popular_accessories
as
select a.name as accessory_name, COUNT(ar.id) as times_rented, SUM(ar.amount) as total_quantity, SUM(ar.price_at_rent) as total_revenue
from accessory a
join accessory_rental ar on a.id = ar.id_accessory
join rental r on ar.id_rental = r.id
where r.status != 'canceled'
group by a.name;

create view v_rv_utilization
as
select rv.spz, b.name as brand_name, t.name as type_name, rv.price_for_day, COUNT(r.id) as total_rentals, SUM(r.date_to - r.date_from) as total_days_rented, AVG(r.date_to - r.date_from) as avg_rental_duration, SUM(r.price) as total_revenue
from rv
left join rental r on rv.id = r.id_rv and r.status != 'canceled'
join brand b on rv.id_brand = b.id
join rv_type t on rv.id_type = t.id
group by rv.spz, b.name, t.name, rv.price_for_day;



commit;