--------------------------------------------------------
--  File created - čtvrtek-ledna-08-2026   
--  Project: Rv-rental-app
--  Author: Martin Chmelík
--  Contact: chmelikmartin123@gmail.com
--------------------------------------------------------
DROP TABLE accessory_rental CASCADE CONSTRAINTS;
DROP TABLE accessory CASCADE CONSTRAINTS;
DROP TABLE rental CASCADE CONSTRAINTS;
DROP TABLE rv CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE rv_type CASCADE CONSTRAINTS;
DROP TABLE brand CASCADE CONSTRAINTS;

DROP VIEW V_CUSTOMER_STATISTICS;
DROP VIEW V_POPULAR_ACCESSORIES;
DROP VIEW V_RENTAL_OVERVIEW;
DROP VIEW V_REVENUE_BY_BRAND;
DROP VIEW V_RV_OVERVIEW;
DROP VIEW V_RV_UTILIZATION;
DROP PROCEDURE CREATE_RENTAL_SIMPLE;
DROP PROCEDURE CREATE_RENTAL_WITH_ACC;
DROP PROCEDURE DELETE_RENTAL_PROC;
--------------------------------------------------------
--  DDL for Table ACCESSORY_RENTAL
--------------------------------------------------------

  CREATE TABLE "ACCESSORY_RENTAL" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ACCESSORY" NUMBER(*,0), 
	"ID_RENTAL" NUMBER(*,0), 
	"AMOUNT" NUMBER(*,0), 
	"PRICE_AT_RENT" NUMBER(10,2)
   ) ;
--------------------------------------------------------
--  DDL for Table ACCESSORY
--------------------------------------------------------

  CREATE TABLE "ACCESSORY" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"PRICE_FOR_DAY" NUMBER(10,2)
   ) ;
--------------------------------------------------------
--  DDL for Table BRAND
--------------------------------------------------------

  CREATE TABLE "BRAND" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "CUSTOMER" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(30 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TEL" VARCHAR2(12 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table RENTAL
--------------------------------------------------------

  CREATE TABLE "RENTAL" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"CREATION_DATE" DATE, 
	"PRICE" NUMBER(10,2), 
	"STATUS" VARCHAR2(20 BYTE), 
	"IS_PAID" NUMBER(1,0), 
	"ID_CUSTOMER" NUMBER(*,0), 
	"ID_RV" NUMBER(*,0)
   ) ;
--------------------------------------------------------
--  DDL for Table RV
--------------------------------------------------------

  CREATE TABLE "RV" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SPZ" VARCHAR2(20 BYTE), 
	"MANUFACTURE_DATE" DATE, 
	"PRICE_FOR_DAY" NUMBER(10,2), 
	"ID_BRAND" NUMBER(*,0), 
	"ID_TYPE" NUMBER(*,0)
   ) ;
--------------------------------------------------------
--  DDL for Table RV_TYPE
--------------------------------------------------------

  CREATE TABLE "RV_TYPE" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(40 BYTE), 
	"DESCRIPTION" VARCHAR2(40 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for View V_CUSTOMER_STATISTICS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_CUSTOMER_STATISTICS" ("CUSTOMER_ID", "CUSTOMER_NAME", "EMAIL", "TOTAL_RENTALS", "TOTAL_SPENT", "AVG_RENTAL_DAYS") AS 
  select c.id as customer_id, c.name || ' ' || c.surname as customer_name, c.email, COUNT(r.id) as total_rentals, SUM(r.price) as total_spent, AVG(r.date_to - r.date_from) as avg_rental_days
from customer c
join rental r on c.id = r.id_customer
group by c.id, c.name, c.surname, c.email
;
--------------------------------------------------------
--  DDL for View V_POPULAR_ACCESSORIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_POPULAR_ACCESSORIES" ("ACCESSORY_NAME", "TIMES_RENTED", "TOTAL_QUANTITY", "TOTAL_REVENUE") AS 
  select a.name as accessory_name, COUNT(ar.id) as times_rented, SUM(ar.amount) as total_quantity, SUM(ar.price_at_rent) as total_revenue
from accessory a
join accessory_rental ar on a.id = ar.id_accessory
join rental r on ar.id_rental = r.id
where r.status != 'canceled'
group by a.name
;
--------------------------------------------------------
--  DDL for View V_RENTAL_OVERVIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RENTAL_OVERVIEW" ("RENTAL_ID", "DATE_FROM", "DATE_TO", "CREATION_DATE", "PRICE", "STATUS", "IS_PAID", "CUSTOMER_NAME", "CUSTOMER_SURNAME", "EMAIL", "RV_SPZ") AS 
  select rental.id as rental_id, rental.date_from, rental.date_to, rental.creation_date, rental.price, rental.status, rental.is_paid, customer.name as customer_name, customer.surname as customer_surname, customer.email, rv.spz as rv_spz
from rental
join customer on rental.id_customer = customer.id
join rv on rental.id_rv = rv.id
;
--------------------------------------------------------
--  DDL for View V_REVENUE_BY_BRAND
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_REVENUE_BY_BRAND" ("BRAND_NAME", "TOTAL_RENTALS", "TOTAL_REVENUE", "AVG_RENTAL_PRICE", "MIN_RENTAL_PRICE", "MAX_RENTAL_PRICE") AS 
  select b.name as brand_name, COUNT(r.id) as total_rentals, SUM(r.price) as total_revenue, AVG(r.price) as avg_rental_price, MIN(r.price) as min_rental_price, MAX(r.price) as max_rental_price
from rental r
join rv on r.id_rv = rv.id
join brand b on rv.id_brand = b.id
where r.status != 'canceled'
group by b.name
;
--------------------------------------------------------
--  DDL for View V_RV_OVERVIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RV_OVERVIEW" ("RV_ID", "SPZ", "MANUFACTURE_DATE", "PRICE_FOR_DAY", "BRAND_NAME", "TYPE_NAME", "TYPE_DESCRIPTION") AS 
  select rv.id as rv_id, rv.spz, rv.manufacture_date, rv.price_for_day, brand.name as brand_name, rv_type.name as type_name, rv_type.description as type_description
from rv
join brand on rv.id_brand = brand.id
join rv_type on rv.id_type = rv_type.id
;
--------------------------------------------------------
--  DDL for View V_RV_UTILIZATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RV_UTILIZATION" ("SPZ", "BRAND_NAME", "TYPE_NAME", "PRICE_FOR_DAY", "TOTAL_RENTALS", "TOTAL_DAYS_RENTED", "AVG_RENTAL_DURATION", "TOTAL_REVENUE") AS 
  select rv.spz, b.name as brand_name, t.name as type_name, rv.price_for_day, COUNT(r.id) as total_rentals, SUM(r.date_to - r.date_from) as total_days_rented, AVG(r.date_to - r.date_from) as avg_rental_duration, SUM(r.price) as total_revenue
from rv
left join rental r on rv.id = r.id_rv and r.status != 'canceled'
join brand b on rv.id_brand = b.id
join rv_type t on rv.id_type = t.id
group by rv.spz, b.name, t.name, rv.price_for_day
;
REM INSERTING into ACCESSORY_RENTAL
SET DEFINE OFF;
Insert into ACCESSORY_RENTAL (ID,ID_ACCESSORY,ID_RENTAL,AMOUNT,PRICE_AT_RENT) values ('1','1','1','1','150');
Insert into ACCESSORY_RENTAL (ID,ID_ACCESSORY,ID_RENTAL,AMOUNT,PRICE_AT_RENT) values ('2','2','1','1','100');
REM INSERTING into ACCESSORY
SET DEFINE OFF;
Insert into ACCESSORY (ID,NAME,DESCRIPTION,PRICE_FOR_DAY) values ('1','Camping Set','Table and 4 chairs','150');
Insert into ACCESSORY (ID,NAME,DESCRIPTION,PRICE_FOR_DAY) values ('2','Bike Rack','For 3 bicycles','100');
Insert into ACCESSORY (ID,NAME,DESCRIPTION,PRICE_FOR_DAY) values ('3','GPS Navigation','Pre-loaded with offline maps','50');
REM INSERTING into BRAND
SET DEFINE OFF;
Insert into BRAND (ID,NAME) values ('1','Volkswagen');
Insert into BRAND (ID,NAME) values ('2','Airstream');
REM INSERTING into CUSTOMER
SET DEFINE OFF;
Insert into CUSTOMER (ID,NAME,SURNAME,EMAIL,TEL) values ('1','John','Doe','john.doe@example.com','477123456');
Insert into CUSTOMER (ID,NAME,SURNAME,EMAIL,TEL) values ('2','Alice','Smith','a.smith@provider.com','779876543');
REM INSERTING into RENTAL
SET DEFINE OFF;
Insert into RENTAL (ID,DATE_FROM,DATE_TO,CREATION_DATE,PRICE,STATUS,IS_PAID,ID_CUSTOMER,ID_RV) values ('1',to_date('01.07.26','DD.MM.RR'),to_date('14.07.26','DD.MM.RR'),to_date('08.01.26','DD.MM.RR'),'35000','reserved','1','1','1');
REM INSERTING into RV
SET DEFINE OFF;
Insert into RV (ID,SPZ,MANUFACTURE_DATE,PRICE_FOR_DAY,ID_BRAND,ID_TYPE) values ('1','RV-99-SKY',to_date('15.05.25','DD.MM.RR'),'2500','1','1');
Insert into RV (ID,SPZ,MANUFACTURE_DATE,PRICE_FOR_DAY,ID_BRAND,ID_TYPE) values ('2','VAN-22-ROAD',to_date('10.01.24','DD.MM.RR'),'1800','2','1');
REM INSERTING into RV_TYPE
SET DEFINE OFF;
Insert into RV_TYPE (ID,NAME,DESCRIPTION) values ('1','Motorhome','Large vehicle with alcove bed');
REM INSERTING into V_CUSTOMER_STATISTICS
SET DEFINE OFF;
Insert into V_CUSTOMER_STATISTICS (CUSTOMER_ID,CUSTOMER_NAME,EMAIL,TOTAL_RENTALS,TOTAL_SPENT,AVG_RENTAL_DAYS) values ('1','John Doe','john.doe@example.com','1','35000','13');
REM INSERTING into V_POPULAR_ACCESSORIES
SET DEFINE OFF;
Insert into V_POPULAR_ACCESSORIES (ACCESSORY_NAME,TIMES_RENTED,TOTAL_QUANTITY,TOTAL_REVENUE) values ('Camping Set','1','1','150');
Insert into V_POPULAR_ACCESSORIES (ACCESSORY_NAME,TIMES_RENTED,TOTAL_QUANTITY,TOTAL_REVENUE) values ('Bike Rack','1','1','100');
REM INSERTING into V_RENTAL_OVERVIEW
SET DEFINE OFF;
Insert into V_RENTAL_OVERVIEW (RENTAL_ID,DATE_FROM,DATE_TO,CREATION_DATE,PRICE,STATUS,IS_PAID,CUSTOMER_NAME,CUSTOMER_SURNAME,EMAIL,RV_SPZ) values ('1',to_date('01.07.26','DD.MM.RR'),to_date('14.07.26','DD.MM.RR'),to_date('08.01.26','DD.MM.RR'),'35000','reserved','1','John','Doe','john.doe@example.com','RV-99-SKY');
REM INSERTING into V_REVENUE_BY_BRAND
SET DEFINE OFF;
Insert into V_REVENUE_BY_BRAND (BRAND_NAME,TOTAL_RENTALS,TOTAL_REVENUE,AVG_RENTAL_PRICE,MIN_RENTAL_PRICE,MAX_RENTAL_PRICE) values ('Volkswagen','1','35000','35000','35000','35000');
REM INSERTING into V_RV_OVERVIEW
SET DEFINE OFF;
Insert into V_RV_OVERVIEW (RV_ID,SPZ,MANUFACTURE_DATE,PRICE_FOR_DAY,BRAND_NAME,TYPE_NAME,TYPE_DESCRIPTION) values ('1','RV-99-SKY',to_date('15.05.25','DD.MM.RR'),'2500','Volkswagen','Motorhome','Large vehicle with alcove bed');
Insert into V_RV_OVERVIEW (RV_ID,SPZ,MANUFACTURE_DATE,PRICE_FOR_DAY,BRAND_NAME,TYPE_NAME,TYPE_DESCRIPTION) values ('2','VAN-22-ROAD',to_date('10.01.24','DD.MM.RR'),'1800','Airstream','Motorhome','Large vehicle with alcove bed');
REM INSERTING into V_RV_UTILIZATION
SET DEFINE OFF;
Insert into V_RV_UTILIZATION (SPZ,BRAND_NAME,TYPE_NAME,PRICE_FOR_DAY,TOTAL_RENTALS,TOTAL_DAYS_RENTED,AVG_RENTAL_DURATION,TOTAL_REVENUE) values ('RV-99-SKY','Volkswagen','Motorhome','2500','1','13','13','35000');
Insert into V_RV_UTILIZATION (SPZ,BRAND_NAME,TYPE_NAME,PRICE_FOR_DAY,TOTAL_RENTALS,TOTAL_DAYS_RENTED,AVG_RENTAL_DURATION,TOTAL_REVENUE) values ('VAN-22-ROAD','Airstream','Motorhome','1800','0',null,null,null);
--------------------------------------------------------
--  DDL for Index SYS_C008792
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008792" ON "ACCESSORY_RENTAL" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008766
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008766" ON "ACCESSORY" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008739
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008739" ON "BRAND" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008761
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008761" ON "CUSTOMER" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008781
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008781" ON "RENTAL" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008752
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008752" ON "RV" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008753
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008753" ON "RV" ("SPZ") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C008743
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008743" ON "RV_TYPE" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Procedure CREATE_RENTAL_SIMPLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CREATE_RENTAL_SIMPLE" (
p_date_from in date,
p_date_to in date,
p_creation_date in date,
p_price in decimal,
p_id_customer in int,
p_id_rv in int
)
as
  v_cnt number;
begin
select count(*) into v_cnt
from rental
where id_rv = p_id_rv and status in ('reserved', 'active')and not (p_date_to   <= date_from or p_date_from >= date_to);

if v_cnt > 0 then
    raise_application_error(-20001, 'RV not available');
  end if;


insert into rental(date_from, date_to, creation_date,rental.price, status, is_paid, id_customer, id_rv)
values (p_date_from, p_date_to, p_creation_date,p_price, 'reserved', 0, p_id_customer, p_id_rv);

commit;
exception
when others then
rollback;
raise;
end;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_RENTAL_WITH_ACC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CREATE_RENTAL_WITH_ACC" (
p_date_from in date,
p_date_to in date,
p_creation_date in date,
p_price in decimal,
p_id_customer in int,
p_id_rv in int,
p_rental_id out int
)
as
v_cnt number;
begin
select count(*) into v_cnt
from rental
where id_rv = p_id_rv and status in ('reserved', 'active') and not (p_date_to <= date_from or p_date_from >= date_to);

if v_cnt > 0 then
raise_application_error(-20001, 'RV not available');
end if;

insert into rental(date_from, date_to, creation_date,price, status, is_paid, id_customer, id_rv)
values (p_date_from, p_date_to, p_creation_date,p_price, 'reserved', 0, p_id_customer, p_id_rv)
returning id into p_rental_id;

commit;
exception
when others then
rollback;
raise;
end;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_RENTAL_PROC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DELETE_RENTAL_PROC" (
p_id_rental in int
)
as
begin
delete from accessory_rental where id_rental = p_id_rental;
delete from rental where id = p_id_rental;

commit;
exception
when others then
rollback;
raise;
end;

/
--------------------------------------------------------
--  Constraints for Table ACCESSORY_RENTAL
--------------------------------------------------------

  ALTER TABLE "ACCESSORY_RENTAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY_RENTAL" MODIFY ("ID_ACCESSORY" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY_RENTAL" MODIFY ("ID_RENTAL" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY_RENTAL" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY_RENTAL" MODIFY ("PRICE_AT_RENT" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY_RENTAL" ADD CHECK (id_accessory > 0) ENABLE;
  ALTER TABLE "ACCESSORY_RENTAL" ADD CHECK (id_rental > 0) ENABLE;
  ALTER TABLE "ACCESSORY_RENTAL" ADD CHECK (amount > 0) ENABLE;
  ALTER TABLE "ACCESSORY_RENTAL" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCESSORY
--------------------------------------------------------

  ALTER TABLE "ACCESSORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY" MODIFY ("PRICE_FOR_DAY" NOT NULL ENABLE);
  ALTER TABLE "ACCESSORY" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table BRAND
--------------------------------------------------------

  ALTER TABLE "BRAND" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BRAND" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BRAND" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table RENTAL
--------------------------------------------------------

  ALTER TABLE "RENTAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("DATE_TO" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("IS_PAID" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("ID_CUSTOMER" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" MODIFY ("ID_RV" NOT NULL ENABLE);
  ALTER TABLE "RENTAL" ADD CHECK (status in ('reserved', 'active', 'finished', 'canceled')) ENABLE;
  ALTER TABLE "RENTAL" ADD CHECK (is_paid in (1, 0)) ENABLE;
  ALTER TABLE "RENTAL" ADD CHECK (id_customer > 0) ENABLE;
  ALTER TABLE "RENTAL" ADD CHECK (id_rv > 0) ENABLE;
  ALTER TABLE "RENTAL" ADD CHECK (date_from < date_to) ENABLE;
  ALTER TABLE "RENTAL" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table RV
--------------------------------------------------------

  ALTER TABLE "RV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RV" MODIFY ("SPZ" NOT NULL ENABLE);
  ALTER TABLE "RV" MODIFY ("MANUFACTURE_DATE" NOT NULL ENABLE);
  ALTER TABLE "RV" MODIFY ("PRICE_FOR_DAY" NOT NULL ENABLE);
  ALTER TABLE "RV" MODIFY ("ID_BRAND" NOT NULL ENABLE);
  ALTER TABLE "RV" MODIFY ("ID_TYPE" NOT NULL ENABLE);
  ALTER TABLE "RV" ADD CHECK (id_brand > 0) ENABLE;
  ALTER TABLE "RV" ADD CHECK (id_type > 0) ENABLE;
  ALTER TABLE "RV" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "RV" ADD UNIQUE ("SPZ")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table RV_TYPE
--------------------------------------------------------

  ALTER TABLE "RV_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RV_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "RV_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "RV_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table RV
--------------------------------------------------------
ALTER TABLE "RV" ADD CONSTRAINT "FK_RV_BRAND" FOREIGN KEY ("ID_BRAND") REFERENCES "BRAND" ("ID") ENABLE;
ALTER TABLE "RV" ADD CONSTRAINT "FK_RV_TYPE" FOREIGN KEY ("ID_TYPE") REFERENCES "RV_TYPE" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table RENTAL
--------------------------------------------------------
ALTER TABLE "RENTAL" ADD CONSTRAINT "FK_RENTAL_CUSTOMER" FOREIGN KEY ("ID_CUSTOMER") REFERENCES "CUSTOMER" ("ID") ENABLE;
ALTER TABLE "RENTAL" ADD CONSTRAINT "FK_RENTAL_RV" FOREIGN KEY ("ID_RV") REFERENCES "RV" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table ACCESSORY_RENTAL
--------------------------------------------------------
ALTER TABLE "ACCESSORY_RENTAL" ADD CONSTRAINT "FK_AR_ACCESSORY" FOREIGN KEY ("ID_ACCESSORY") REFERENCES "ACCESSORY" ("ID") ENABLE;
ALTER TABLE "ACCESSORY_RENTAL" ADD CONSTRAINT "FK_AR_RENTAL" FOREIGN KEY ("ID_RENTAL") REFERENCES "RENTAL" ("ID") ENABLE;

  COMMIT;